modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="magicofdye"
version="${version}"
displayName="Magic of Dye"
authors="Codex"
description='''
Color magic system inspired by Dye depot.
'''

[[dependencies.magicofdye]]
modId="neoforge"
type="required"
versionRange="[21.1.172,)"
ordering="NONE"
side="BOTH"

[[dependencies.magicofdye]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
